apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  HostName: {{ .Values.MessageBroker.RabbitMQ.HostName | b64enc }}  
  UserName: {{ .Values.MessageBroker.RabbitMQ.UserName | b64enc }} 
  Password: {{ .Values.MessageBroker.RabbitMQ.Password | b64enc }}